package org.onvif.client;

public enum DirectionEnum {
    PTZ_CMD_LEFT, PTZ_CMD_RIGHT, PTZ_CMD_UP, PTZ_CMD_DOWN, PTZ_CMD_LEFTUP, PTZ_CMD_LEFTDOWN, PTZ_CMD_RIGHTUP, PTZ_CMD_RIGHTDOWN, PTZ_CMD_ZOOM_IN, PTZ_CMD_ZOOM_OUT;
}
